### ISSUE TITLE
Transform shortcuts in animation keyframes

### ISSUE THREAD

**Issue by jaydenseric** [jonathantneal/postcss-transform-shortcut#7]
Is this suported, and if not, could we add support for this?

``` css
@keyframes test {
  0% {
    scale: 0;
  }
  50% {
    rotate: 90deg;
  }
  100% {
    scale: 2;
  }
}
```

Should compile to:

``` css
@keyframes test {
  0% {
    transform: scale(0);
  }
  50% {
    transform:  scale(1) rotate(90deg);
  }
  100% {
    transform:  scale(2);
  }
}
```

I don't expect this to work when combining animations, just within one keyframes declaration.

Manually doing the calculations when combining several transform operations in one animation is really hard and annoying. This is the primary use case for the new transform properties and to be able to use them in this way now would be beyond awesome.
